"""Diagnostic trouble code descriptions.

Generic (SAE J2012) codes apply to every OBD-II vehicle. Manufacturer codes
(P1xxx, B1xxx, C1xxx, U1xxx …) only mean something for the make they came
from, so they are looked up per make.

You can add or override descriptions without touching the code: create
``dtc_custom.csv`` next to this file with lines like ``P1234;My description``.
"""

from __future__ import annotations

import csv
from pathlib import Path

GENERIC: dict[str, str] = {
    # Fuel and air metering
    "P0010": "Intake camshaft position actuator circuit (Bank 1)",
    "P0011": "Intake camshaft timing over-advanced / system performance (Bank 1)",
    "P0012": "Intake camshaft timing over-retarded (Bank 1)",
    "P0013": "Exhaust camshaft position actuator circuit (Bank 1)",
    "P0014": "Exhaust camshaft timing over-advanced / system performance (Bank 1)",
    "P0016": "Crankshaft / camshaft position correlation (Bank 1 Sensor A)",
    "P0017": "Crankshaft / camshaft position correlation (Bank 1 Sensor B)",
    "P0018": "Crankshaft / camshaft position correlation (Bank 2 Sensor A)",
    "P0019": "Crankshaft / camshaft position correlation (Bank 2 Sensor B)",
    "P0020": "Intake camshaft position actuator circuit (Bank 2)",
    "P0021": "Intake camshaft timing over-advanced / system performance (Bank 2)",
    "P0022": "Intake camshaft timing over-retarded (Bank 2)",
    "P0030": "HO2S heater control circuit (Bank 1 Sensor 1)",
    "P0031": "HO2S heater control circuit low (Bank 1 Sensor 1)",
    "P0032": "HO2S heater control circuit high (Bank 1 Sensor 1)",
    "P0036": "HO2S heater control circuit (Bank 1 Sensor 2)",
    "P0037": "HO2S heater control circuit low (Bank 1 Sensor 2)",
    "P0038": "HO2S heater control circuit high (Bank 1 Sensor 2)",
    "P0050": "HO2S heater control circuit (Bank 2 Sensor 1)",
    "P0051": "HO2S heater control circuit low (Bank 2 Sensor 1)",
    "P0052": "HO2S heater control circuit high (Bank 2 Sensor 1)",
    "P0056": "HO2S heater control circuit (Bank 2 Sensor 2)",
    "P0057": "HO2S heater control circuit low (Bank 2 Sensor 2)",
    "P0058": "HO2S heater control circuit high (Bank 2 Sensor 2)",
    "P0068": "MAP / MAF – throttle position correlation",
    "P0087": "Fuel rail / system pressure too low",
    "P0088": "Fuel rail / system pressure too high",
    "P0090": "Fuel pressure regulator 1 control circuit",
    "P0100": "Mass or volume air flow circuit",
    "P0101": "Mass or volume air flow circuit range / performance",
    "P0102": "Mass or volume air flow circuit low input",
    "P0103": "Mass or volume air flow circuit high input",
    "P0104": "Mass or volume air flow circuit intermittent",
    "P0105": "Manifold absolute pressure / barometric pressure circuit",
    "P0106": "Manifold absolute pressure / barometric pressure circuit range / performance",
    "P0107": "Manifold absolute pressure / barometric pressure circuit low input",
    "P0108": "Manifold absolute pressure / barometric pressure circuit high input",
    "P0110": "Intake air temperature sensor 1 circuit",
    "P0111": "Intake air temperature sensor 1 circuit range / performance",
    "P0112": "Intake air temperature sensor 1 circuit low",
    "P0113": "Intake air temperature sensor 1 circuit high",
    "P0115": "Engine coolant temperature circuit",
    "P0116": "Engine coolant temperature circuit range / performance",
    "P0117": "Engine coolant temperature circuit low",
    "P0118": "Engine coolant temperature circuit high",
    "P0120": "Throttle / pedal position sensor A circuit",
    "P0121": "Throttle / pedal position sensor A circuit range / performance",
    "P0122": "Throttle / pedal position sensor A circuit low",
    "P0123": "Throttle / pedal position sensor A circuit high",
    "P0125": "Insufficient coolant temperature for closed-loop fuel control",
    "P0128": "Coolant thermostat (coolant temperature below thermostat regulating temperature)",
    "P0130": "O2 sensor circuit (Bank 1 Sensor 1)",
    "P0131": "O2 sensor circuit low voltage (Bank 1 Sensor 1)",
    "P0132": "O2 sensor circuit high voltage (Bank 1 Sensor 1)",
    "P0133": "O2 sensor circuit slow response (Bank 1 Sensor 1)",
    "P0134": "O2 sensor circuit no activity detected (Bank 1 Sensor 1)",
    "P0135": "O2 sensor heater circuit (Bank 1 Sensor 1)",
    "P0136": "O2 sensor circuit (Bank 1 Sensor 2)",
    "P0137": "O2 sensor circuit low voltage (Bank 1 Sensor 2)",
    "P0138": "O2 sensor circuit high voltage (Bank 1 Sensor 2)",
    "P0139": "O2 sensor circuit slow response (Bank 1 Sensor 2)",
    "P0140": "O2 sensor circuit no activity detected (Bank 1 Sensor 2)",
    "P0141": "O2 sensor heater circuit (Bank 1 Sensor 2)",
    "P0150": "O2 sensor circuit (Bank 2 Sensor 1)",
    "P0151": "O2 sensor circuit low voltage (Bank 2 Sensor 1)",
    "P0152": "O2 sensor circuit high voltage (Bank 2 Sensor 1)",
    "P0153": "O2 sensor circuit slow response (Bank 2 Sensor 1)",
    "P0154": "O2 sensor circuit no activity detected (Bank 2 Sensor 1)",
    "P0155": "O2 sensor heater circuit (Bank 2 Sensor 1)",
    "P0156": "O2 sensor circuit (Bank 2 Sensor 2)",
    "P0157": "O2 sensor circuit low voltage (Bank 2 Sensor 2)",
    "P0158": "O2 sensor circuit high voltage (Bank 2 Sensor 2)",
    "P0159": "O2 sensor circuit slow response (Bank 2 Sensor 2)",
    "P0160": "O2 sensor circuit no activity detected (Bank 2 Sensor 2)",
    "P0161": "O2 sensor heater circuit (Bank 2 Sensor 2)",
    "P0170": "Fuel trim (Bank 1)",
    "P0171": "System too lean (Bank 1)",
    "P0172": "System too rich (Bank 1)",
    "P0173": "Fuel trim (Bank 2)",
    "P0174": "System too lean (Bank 2)",
    "P0175": "System too rich (Bank 2)",
    "P0180": "Fuel temperature sensor A circuit",
    "P0190": "Fuel rail pressure sensor circuit",
    "P0191": "Fuel rail pressure sensor circuit range / performance",
    "P0192": "Fuel rail pressure sensor circuit low",
    "P0193": "Fuel rail pressure sensor circuit high",
    "P0196": "Engine oil temperature sensor range / performance",
    "P0197": "Engine oil temperature sensor low",
    "P0198": "Engine oil temperature sensor high",
    # Injector circuits
    "P0200": "Injector circuit / open",
    "P0201": "Injector circuit / open – cylinder 1",
    "P0202": "Injector circuit / open – cylinder 2",
    "P0203": "Injector circuit / open – cylinder 3",
    "P0204": "Injector circuit / open – cylinder 4",
    "P0205": "Injector circuit / open – cylinder 5",
    "P0206": "Injector circuit / open – cylinder 6",
    "P0207": "Injector circuit / open – cylinder 7",
    "P0208": "Injector circuit / open – cylinder 8",
    "P0217": "Engine coolant over-temperature condition",
    "P0218": "Transmission fluid over-temperature condition",
    "P0219": "Engine over-speed condition",
    "P0220": "Throttle / pedal position sensor B circuit",
    "P0221": "Throttle / pedal position sensor B circuit range / performance",
    "P0222": "Throttle / pedal position sensor B circuit low",
    "P0223": "Throttle / pedal position sensor B circuit high",
    "P0230": "Fuel pump primary circuit",
    "P0234": "Turbocharger / supercharger overboost condition",
    "P0235": "Turbocharger boost sensor A circuit",
    "P0236": "Turbocharger boost sensor A circuit range / performance",
    "P0237": "Turbocharger boost sensor A circuit low",
    "P0238": "Turbocharger boost sensor A circuit high",
    "P0243": "Turbocharger wastegate solenoid A",
    "P0245": "Turbocharger wastegate solenoid A low",
    "P0246": "Turbocharger wastegate solenoid A high",
    "P0261": "Cylinder 1 injector circuit low",
    "P0262": "Cylinder 1 injector circuit high",
    "P0299": "Turbocharger / supercharger underboost",
    # Ignition / misfire
    "P0300": "Random / multiple cylinder misfire detected",
    "P0301": "Cylinder 1 misfire detected",
    "P0302": "Cylinder 2 misfire detected",
    "P0303": "Cylinder 3 misfire detected",
    "P0304": "Cylinder 4 misfire detected",
    "P0305": "Cylinder 5 misfire detected",
    "P0306": "Cylinder 6 misfire detected",
    "P0307": "Cylinder 7 misfire detected",
    "P0308": "Cylinder 8 misfire detected",
    "P0309": "Cylinder 9 misfire detected",
    "P0310": "Cylinder 10 misfire detected",
    "P0315": "Crankshaft position system variation not learned",
    "P0316": "Misfire detected on start-up (first 1000 revolutions)",
    "P0320": "Ignition / distributor engine speed input circuit",
    "P0325": "Knock sensor 1 circuit (Bank 1 or single sensor)",
    "P0326": "Knock sensor 1 circuit range / performance (Bank 1 or single sensor)",
    "P0327": "Knock sensor 1 circuit low (Bank 1 or single sensor)",
    "P0328": "Knock sensor 1 circuit high (Bank 1 or single sensor)",
    "P0330": "Knock sensor 2 circuit (Bank 2)",
    "P0332": "Knock sensor 2 circuit low (Bank 2)",
    "P0333": "Knock sensor 2 circuit high (Bank 2)",
    "P0335": "Crankshaft position sensor A circuit",
    "P0336": "Crankshaft position sensor A circuit range / performance",
    "P0337": "Crankshaft position sensor A circuit low",
    "P0338": "Crankshaft position sensor A circuit high",
    "P0339": "Crankshaft position sensor A circuit intermittent",
    "P0340": "Camshaft position sensor A circuit (Bank 1 or single sensor)",
    "P0341": "Camshaft position sensor A circuit range / performance (Bank 1 or single sensor)",
    "P0342": "Camshaft position sensor A circuit low (Bank 1 or single sensor)",
    "P0343": "Camshaft position sensor A circuit high (Bank 1 or single sensor)",
    "P0345": "Camshaft position sensor A circuit (Bank 2)",
    "P0350": "Ignition coil primary / secondary circuit",
    "P0351": "Ignition coil A primary / secondary circuit",
    "P0352": "Ignition coil B primary / secondary circuit",
    "P0353": "Ignition coil C primary / secondary circuit",
    "P0354": "Ignition coil D primary / secondary circuit",
    "P0355": "Ignition coil E primary / secondary circuit",
    "P0356": "Ignition coil F primary / secondary circuit",
    "P0357": "Ignition coil G primary / secondary circuit",
    "P0358": "Ignition coil H primary / secondary circuit",
    "P0365": "Camshaft position sensor B circuit (Bank 1)",
    "P0380": "Glow plug / heater circuit A",
    "P0390": "Camshaft position sensor B circuit (Bank 2)",
    # Auxiliary emission controls
    "P0400": "Exhaust gas recirculation flow",
    "P0401": "Exhaust gas recirculation flow insufficient detected",
    "P0402": "Exhaust gas recirculation flow excessive detected",
    "P0403": "Exhaust gas recirculation control circuit",
    "P0404": "Exhaust gas recirculation control circuit range / performance",
    "P0405": "Exhaust gas recirculation sensor A circuit low",
    "P0406": "Exhaust gas recirculation sensor A circuit high",
    "P0410": "Secondary air injection system",
    "P0411": "Secondary air injection system incorrect flow detected",
    "P0420": "Catalyst system efficiency below threshold (Bank 1)",
    "P0421": "Warm-up catalyst efficiency below threshold (Bank 1)",
    "P0430": "Catalyst system efficiency below threshold (Bank 2)",
    "P0431": "Warm-up catalyst efficiency below threshold (Bank 2)",
    "P0440": "Evaporative emission system",
    "P0441": "Evaporative emission system incorrect purge flow",
    "P0442": "Evaporative emission system leak detected (small leak)",
    "P0443": "Evaporative emission system purge control valve circuit",
    "P0446": "Evaporative emission system vent control circuit",
    "P0449": "Evaporative emission system vent valve / solenoid circuit",
    "P0451": "Evaporative emission system pressure sensor / switch range / performance",
    "P0452": "Evaporative emission system pressure sensor / switch low",
    "P0453": "Evaporative emission system pressure sensor / switch high",
    "P0455": "Evaporative emission system leak detected (large leak / no flow)",
    "P0456": "Evaporative emission system leak detected (very small leak)",
    "P0457": "Evaporative emission system leak detected (fuel cap loose / off)",
    "P0460": "Fuel level sensor A circuit",
    "P0461": "Fuel level sensor A circuit range / performance",
    "P0462": "Fuel level sensor A circuit low",
    "P0463": "Fuel level sensor A circuit high",
    "P0480": "Fan 1 control circuit",
    "P0481": "Fan 2 control circuit",
    "P0496": "Evaporative emission system high purge flow",
    # Speed, idle control, auxiliary inputs
    "P0500": "Vehicle speed sensor A",
    "P0501": "Vehicle speed sensor A range / performance",
    "P0503": "Vehicle speed sensor A intermittent / erratic / high",
    "P0505": "Idle air control system",
    "P0506": "Idle air control system RPM lower than expected",
    "P0507": "Idle air control system RPM higher than expected",
    "P0520": "Engine oil pressure sensor / switch circuit",
    "P0521": "Engine oil pressure sensor / switch range / performance",
    "P0522": "Engine oil pressure sensor / switch low voltage",
    "P0523": "Engine oil pressure sensor / switch high voltage",
    "P0530": "A/C refrigerant pressure sensor A circuit",
    "P0532": "A/C refrigerant pressure sensor A circuit low",
    "P0533": "A/C refrigerant pressure sensor A circuit high",
    "P0562": "System voltage low",
    "P0563": "System voltage high",
    "P0571": "Brake switch A circuit",
    "P0600": "Serial communication link",
    "P0601": "Internal control module memory checksum error",
    "P0602": "Control module programming error",
    "P0603": "Internal control module keep-alive memory (KAM) error",
    "P0604": "Internal control module random access memory (RAM) error",
    "P0605": "Internal control module read-only memory (ROM) error",
    "P0606": "Control module processor",
    "P0607": "Control module performance",
    "P0620": "Generator control circuit",
    "P0622": "Generator field terminal circuit",
    "P0625": "Generator field terminal circuit low",
    "P0626": "Generator field terminal circuit high",
    "P0627": "Fuel pump A control circuit / open",
    "P0641": "Sensor reference voltage A circuit / open",
    "P0645": "A/C clutch relay control circuit",
    "P0651": "Sensor reference voltage B circuit / open",
    # Transmission
    "P0700": "Transmission control system (MIL request) – read the TCM for details",
    "P0705": "Transmission range sensor A circuit (PRNDL input)",
    "P0706": "Transmission range sensor A circuit range / performance",
    "P0710": "Transmission fluid temperature sensor A circuit",
    "P0711": "Transmission fluid temperature sensor A circuit range / performance",
    "P0712": "Transmission fluid temperature sensor A circuit low",
    "P0713": "Transmission fluid temperature sensor A circuit high",
    "P0715": "Input / turbine speed sensor A circuit",
    "P0717": "Input / turbine speed sensor A circuit no signal",
    "P0720": "Output speed sensor circuit",
    "P0721": "Output speed sensor circuit range / performance",
    "P0722": "Output speed sensor circuit no signal",
    "P0729": "Gear 6 incorrect ratio",
    "P0730": "Incorrect gear ratio",
    "P0731": "Gear 1 incorrect ratio",
    "P0732": "Gear 2 incorrect ratio",
    "P0733": "Gear 3 incorrect ratio",
    "P0734": "Gear 4 incorrect ratio",
    "P0735": "Gear 5 incorrect ratio",
    "P0740": "Torque converter clutch solenoid circuit / open",
    "P0741": "Torque converter clutch solenoid circuit performance / stuck off",
    "P0742": "Torque converter clutch solenoid circuit stuck on",
    "P0743": "Torque converter clutch solenoid circuit electrical",
    "P0750": "Shift solenoid A",
    "P0755": "Shift solenoid B",
    "P0760": "Shift solenoid C",
    "P0765": "Shift solenoid D",
    "P0770": "Shift solenoid E",
    "P0780": "Shift error",
    "P0868": "Transmission fluid pressure low",
    # P2 generic
    "P2004": "Intake manifold runner control stuck open (Bank 1)",
    "P2006": "Intake manifold runner control stuck closed (Bank 1)",
    "P2096": "Post-catalyst fuel trim system too lean (Bank 1)",
    "P2097": "Post-catalyst fuel trim system too rich (Bank 1)",
    "P2098": "Post-catalyst fuel trim system too lean (Bank 2)",
    "P2099": "Post-catalyst fuel trim system too rich (Bank 2)",
    "P2101": "Throttle actuator control motor circuit range / performance",
    "P2104": "Throttle actuator control system – forced idle",
    "P2105": "Throttle actuator control system – forced engine shutdown",
    "P2106": "Throttle actuator control system – forced limited power",
    "P2110": "Throttle actuator control system – forced limited RPM",
    "P2111": "Throttle actuator control system – stuck open",
    "P2112": "Throttle actuator control system – stuck closed",
    "P2122": "Pedal position sensor D circuit low",
    "P2123": "Pedal position sensor D circuit high",
    "P2127": "Pedal position sensor E circuit low",
    "P2128": "Pedal position sensor E circuit high",
    "P2135": "Throttle / pedal position sensor A / B voltage correlation",
    "P2138": "Pedal position sensor D / E voltage correlation",
    "P2177": "System too lean off idle (Bank 1)",
    "P2178": "System too rich off idle (Bank 1)",
    "P2179": "System too lean off idle (Bank 2)",
    "P2180": "System too rich off idle (Bank 2)",
    "P2187": "System too lean at idle (Bank 1)",
    "P2188": "System too rich at idle (Bank 1)",
    "P2189": "System too lean at idle (Bank 2)",
    "P2190": "System too rich at idle (Bank 2)",
    "P2195": "O2 sensor signal stuck lean (Bank 1 Sensor 1)",
    "P2196": "O2 sensor signal stuck rich (Bank 1 Sensor 1)",
    "P2197": "O2 sensor signal stuck lean (Bank 2 Sensor 1)",
    "P2198": "O2 sensor signal stuck rich (Bank 2 Sensor 1)",
    "P2270": "O2 sensor signal stuck lean (Bank 1 Sensor 2)",
    "P2271": "O2 sensor signal stuck rich (Bank 1 Sensor 2)",
    "P2272": "O2 sensor signal stuck lean (Bank 2 Sensor 2)",
    "P2273": "O2 sensor signal stuck rich (Bank 2 Sensor 2)",
    "P2279": "Intake air system leak",
    "P2400": "Evaporative emission system leak detection pump control circuit / open",
    "P2401": "Evaporative emission system leak detection pump control circuit low",
    "P2402": "Evaporative emission system leak detection pump control circuit high",
    "P2A00": "O2 sensor circuit range / performance (Bank 1 Sensor 1)",
    "P2A03": "O2 sensor circuit range / performance (Bank 2 Sensor 1)",
    # Network
    "U0001": "High-speed CAN communication bus",
    "U0073": "Control module communication bus A off",
    "U0100": "Lost communication with ECM / PCM A",
    "U0101": "Lost communication with TCM",
    "U0121": "Lost communication with anti-lock brake system (ABS) control module",
    "U0131": "Lost communication with power steering control module",
    "U0140": "Lost communication with body control module",
    "U0151": "Lost communication with restraints control module",
    "U0155": "Lost communication with instrument panel cluster (IPC) control module",
    "U0164": "Lost communication with HVAC control module",
    "U0184": "Lost communication with radio",
    "U0401": "Invalid data received from ECM / PCM A",
    "U0402": "Invalid data received from TCM",
    "U0415": "Invalid data received from anti-lock brake system (ABS) control module",
    "U0422": "Invalid data received from body control module",
}

# Manufacturer-specific codes, only shown for the matching make.
MANUFACTURER: dict[str, dict[str, str]] = {
    "Ford": {
        "P1000": "OBD-II monitor testing not complete (normal after clearing codes or battery disconnect)",
        "P1001": "KOER self-test not able to complete",
        "P1131": "Lack of upstream HO2S switch – adaptive fuel limit, sensor indicates lean (Bank 1)",
        "P1132": "Lack of upstream HO2S switch – sensor indicates rich (Bank 1)",
        "P1151": "Lack of upstream HO2S switch – adaptive fuel limit, sensor indicates lean (Bank 2)",
        "P1152": "Lack of upstream HO2S switch – sensor indicates rich (Bank 2)",
        "P1260": "Theft detected – vehicle immobilized",
        "P1299": "Cylinder head over-temperature protection active",
        "P1450": "Unable to bleed up fuel tank vacuum",
        "P1633": "Keep-alive power voltage too low",
        "P1744": "Torque converter clutch system performance",
        "P1783": "Transmission over-temperature condition",
    },
}

SYSTEMS = {"P": "Powertrain", "C": "Chassis", "B": "Body", "U": "Network"}

P_SUBSYSTEMS = {
    "0": "fuel and air metering / auxiliary emission controls",
    "1": "fuel and air metering",
    "2": "fuel and air metering (injector circuit)",
    "3": "ignition system or misfire",
    "4": "auxiliary emission controls",
    "5": "vehicle speed, idle control and auxiliary inputs",
    "6": "computer and output circuits",
    "7": "transmission",
    "8": "transmission",
    "9": "transmission",
    "A": "hybrid propulsion",
    "B": "hybrid propulsion",
    "C": "hybrid propulsion",
}

_CUSTOM: dict[str, str] | None = None


def _custom() -> dict[str, str]:
    global _CUSTOM
    if _CUSTOM is None:
        _CUSTOM = {}
        path = Path(__file__).resolve().parent / "dtc_custom.csv"
        if path.exists():
            with path.open(encoding="utf-8-sig", newline="") as handle:
                for row in csv.reader(handle, delimiter=";"):
                    if len(row) >= 2 and row[0].strip():
                        _CUSTOM[row[0].strip().upper()] = row[1].strip()
    return _CUSTOM


def is_manufacturer_specific(code: str) -> bool:
    """SAE J2012: P1xxx, P30xx-P33xx, and B/C/U 1xxx-2xxx are manufacturer-controlled."""
    if len(code) < 3:
        return False
    if code[1] == "1":
        return True
    if code[0] == "P":
        return code[1] == "3" and code[2] in "0123"
    return code[1] == "2"


def describe_dtc(code: str, make: str = "") -> str:
    code = code.upper()[:5]
    if code in _custom():
        return _custom()[code]
    if make and code in MANUFACTURER.get(make, {}):
        return MANUFACTURER[make][code]
    if code in GENERIC:
        return GENERIC[code]

    system = SYSTEMS.get(code[:1], "Unknown system")
    if is_manufacturer_specific(code):
        owner = f"{make} " if make else ""
        return f"{owner}manufacturer-specific {system.lower()} code (see service information)"
    if code[:1] == "P" and len(code) >= 3:
        return f"Generic powertrain code – {P_SUBSYSTEMS.get(code[2], 'unclassified')}"
    return f"Generic {system.lower()} code"
